#server.port=8090
#server.servlet.context-path=/admin
#
#name=lkw
#age=28
#
#content="name:${name},age:${age}


server:
  port: 8090
  servlet:
    context-path: /admin

name: Liukangwen
age: 28
#无关紧要
content: "name:${name},age:${age}"

#热部署生效
spring.devtools.restart.enabled: true
#设置重启的目录
spring.devtools.restart.additional-paths: src/main/java
#classpath目录下的WEB-INF文件夹内容修改不重启
spring.devtools.restart.exclude: WEB-INF/**

logging:
# 可以
#  config: classpath:log4j2/log4j2.xml
#  properties失败
#  config: classpath:log4j2/log4j2.properties
#  可以
  config: classpath:log4j2/log4j2.yml

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


  cache:
    type: redis
    redis:
      database: 0
      host: 192.168.226.5
      port: 6379
      # 有密码填密码，没有密码不填
      password:
      # 连接超时时间（ms)
      timeout: 1000ms
      # 高版本springboot中使用jedis或者lettuce
      jedis:
        pool:
          # 连接池最大连接数（负值表示无限制）
          max-active: 8
          # 连接池最大阻塞等待时间（负值无限制)
          max-wait: 5000ms
          # 最大空闲链接数
          max-idle: 8
          # 最小空闲链接数
          min-idle: 0

#mybatis-plus
mybatis-plus:
    global-config:
      db-config:
        id-type: auto
        field-strategy: not_empty
        #驼峰下划线转换
        column-underline: true
        #逻辑删除配置
        logic-delete-value: 0
        logic-not-delete-value: 1
        db-type: mysql
      refresh: false
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com/example/demo/entity
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false





